### ISSUE TITLE
default_home set to an empty value uses the default value

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1625]
If ```default_home``` is set to an empty value using ```default_home: []``` Invidious will crash when starting.

The config I use: https://github.com/TheFrenchGhosty/PussTheCat.org-Configs/blob/master/Services/Invidious/config.yml

**Comment by saltycrys** [comment]
The value of `default_home` is expected to be a string and `[]` is an empty array.
Does it crash with an empty string like `default_home: ""`?

**Comment by TheFrenchGhosty** [comment]
@saltycrys I just tried and it indeed doesn't crash, however it assume it's set to popular, and redirect to popular.

Any reason why it doesn't work with ```[]``` but ```feed_menu``` does?

**Comment by saltycrys** [comment]
Crystal is a strongly typed language, which means that all possible types of a value must be known at compile time.

When Invidious loads values from the config file it parses them into the types defined in the `Config` class: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L64-L116

`default_home` is in `default_user_preferences` which has a type of `ConfigPreferences`: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L82

The `ConfigPreferences` struct: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L25-L62

`default_home`'s type is `String`: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L45

`feed_menu`'s type is `Array(String)` (note that an empty array is an array of strings with no elements): https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L46

<hr>

`|` means `or` so `use_pubsub_feeds` can be either `Bool` or `Int32`: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L74

A type followed by a question mark like `Bool?` is sugar for `Bool | nil`, so `https_only` can either be a bool or an empty/nil/null value: https://github.com/iv-org/invidious/blob/b19524d56a49c01ec72deb33bfb423ac25721ffc/src/invidious/helpers/helpers.cr#L71

<hr>

YAML scalars are insane but luckily YAML is a superset of JSON, so to keep things simple always write scalars as valid JSON (except strings and fancy numbers, so really just null and bools):
```yaml
good:
  explicit_null: null
  lowercase_true: true
  lowercase_false: false
bad:
  implicit_null:
  null_symbol: ~
  non_lowercase_null:
    - Null
    - NULL
  non_lowercase_bools:
    - True
    - TRUE
    - False
    - FALSE
  pre_yaml_1.2_bools:
    - yes
    - Yes
    - YES
    - no
    - No
    - NO
```

If you're interested in YAMLs [63 ways of writing multi-line strings](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines/21699210#21699210) check out [this helpful website](https://yaml-multiline.info/).
