### ISSUE TITLE
HTTP 502 error when trying to set an administrator

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1632]
Hello,

According the doc, i have to set the parameter "admins" to my ID to be an administrator. But the said parameter appears nowhere in my own config file, among others parameters mentioned in the doc. I only have this:

```
channel_threads: 1
feed_threads: 1

db:
  user: invidious
  password: AZcw2FmefMoGy5n9jYUAAmmD5HVv2f
  host: localhost
  port: 5432
  dbname: invidious

full_refresh: false
https_only: true
domain:
port: 3002
host_binding: 127.0.0.1

#https://github.com/iv-org/invidious/blob/5c6911065845d2724c7826f3d663a6ee6c7d4774/src/invidious/helpers/helpe$
default_user_preferences:
  dark_mode: true
  local: true
  locale: "fr"
  comments: ["youtube",""]
```

And that's all, there is nothing else in the file. So i added manually the parameter with my own username as argument, then i restarded the service. The result: error 502 bad gateway. I deleted the parameter, restarted the service, then everything works again.
