### ISSUE TITLE
[Enhancement] Video cover entire player area (ie. No black bars)

### ISSUE THREAD

**Issue by stranger-danger-zamu** [iv-org/invidious#1880]
**Is your enhancement request related to a problem? Please describe.**
Videos have black bars instead of scaling to cover whatever space they need to fit into the browser window.

**Describe the solution you'd like**
Changing the `/assests/css/default.css` file to make videos cover the space and have no black bars.
Specifically the changes needed to achieve this are:
```css
diff --git a/assets/css/default.css b/assets/css/default.css
index 793295d..8c70960 100644
--- a/assets/css/default.css
+++ b/assets/css/default.css
@@ -237,11 +237,11 @@ input[type="search"]::-webkit-search-cancel-button {
 
 @media only screen and (max-aspect-ratio: 16/9) {
   .player-dimensions.vjs-fluid {
-    padding-top: 46.86% !important;
+/*     padding-top: 46.86% !important; */
   }
 
   #player-container {
-    padding-bottom: 46.86% !important;
+/*     padding-bottom: 46.86% !important; */
   }
 }
 
@@ -453,7 +453,7 @@ span > select {
 }
 
 .player-dimensions.vjs-fluid {
-  padding-top: 82vh;
+/*   padding-top: 82vh; */
 }
 
 video.video-js {
@@ -463,8 +463,8 @@ video.video-js {
 
 #player-container {
   position: relative;
-  padding-bottom: 82vh;
-  height: 0;
+/*   padding-bottom: 82vh; */
+/*   height: 0; */
 }
 
 .pure-control-group label {
@@ -630,4 +630,4 @@ body.dark-theme {
 
 #filters {
   display: none;
-}
\ No newline at end of file
+}
```

**Describe alternatives you've considered**
Something like a user setting that allows the addition of custom user CSS that gets evaluated last. 

**Additional context**
I just commented out the CSS blocks necessary and haven't done thorough testing to see if it breaks any other features. I did however use Google Chrome's device toolbar to emulate all the devices and checked for any weirdness. From what I can tell it worked perfectly fine. 

Also didn't submit this as a PR since I wasn't sure if this was done for some reason.
