### ISSUE TITLE
[Enhancement] Docker - Document it, make an user focussed compose file

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1903]
**Is your enhancement request related to a problem? Please describe.**

- Quay isn't talked about.
- Dockerhub need to be properly deprecated, and its use strongly discouraged with an announcement.
- A docker-compose made for administrators needs to be created and added to the documentation.

**Describe the solution you'd like**

Documentation.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by dayvista** [comment]
I could take a stab at this based on the configuration [here](https://github.com/iv-org/invidious/issues/1895#issuecomment-812642053).

Just two questions first:

1. Is [this](https://github.com/iv-org/documentation/blob/master/Installation.md#docker) the section in the docs that should be edited?
2. What is the reasoning for moving away from Dockerhub and using Quay instead? I've only just heard about Quay through this project. I imagine it has something to do with privacy/code ownership/etc.

**Comment by TheFrenchGhosty** [comment]
>1. Is this the section in the docs that should be edited?

Yes.

>2. What is the reasoning for moving away from Dockerhub and using Quay instead?

The main reason is that we don't have access to the Dockerhub image, and then I discovered that Quay is open source, so it's actually better for a project like Invidious that is focused on privacy.

**Comment by TheFrenchGhosty** [comment]
Compose shared to me a while ago by @unixfox as a resource to make the new compose (if you work on this issue @dayvista you might find this useful):

```
version: '2.4'
services:
    postgres:
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_POSTGRES_PASSWORD=password
        networks:
            - default
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        image: postgres:10
        volumes:
            - './postgres:/var/lib/postgresql/data'
            - '/etc/localtime:/etc/localtime:ro'
    invidious:
        restart: always
        mem_limit: 1024M
        cpus: 0.5
        image: quay.io/invidious/invidious
        networks:
            - default
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './config:/invidious/config'

networks:
    default:
```

**Comment by dayvista** [comment]
Thanks. I'll make an effort to get to it in the next couple days.

**Comment by namazso** [comment]
here's mine, i was advised to post it here a while ago:

```
version: '2.4'
services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kemal"]
  invidious:
    image: quay.io/invidious/invidious
    restart: unless-stopped
    mem_limit: 2048M
    cpus: 4
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:3000/channel/namazso"]
    logging:
      driver: none
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 4
        check_tables: true
        feed_threads: 4
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        login_enabled: false
        registration_enabled: false
        statistics_enabled: true
        full_refresh: false
        https_only: true
        domain: invidious.namazso.eu
        pool_size: 1000
        external_port: 443
        default_user_preferences:
          dark_mode: true
          quality: dash
    depends_on:
      - postgres
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=invidious.namazso.eu
      - LETSENCRYPT_HOST=invidious.namazso.eu
    networks:
      - default
      - public_services

networks:
  public_services:
    external: true
```
