### ISSUE TITLE
Invidious behind Traefik reverse-proxy published not as domain but path

### ISSUE THREAD

**Issue by v-bulynkin** [iv-org/invidious#2045]
Hello everyone,

Is it possible to expose Invidious not as domain behind a reverse-proxy but as path?

For example, I have a test domain https://docker, where Wordpress is located at **/** and Invidious at **/youtube.**

I made the following settings in the docker-compose.yml:
```yaml
        https_only: true
        external_port: 443
        domain: docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.invidious-http.rule=PathPrefix(`/youtube`)
      - traefik.http.routers.invidious-http.entrypoints=web
      - traefik.http.routers.invidious-http.middlewares=ssl
      - traefik.http.middlewares.ssl.redirectscheme.scheme=https
      - traefik.http.routers.invidious.rule=PathPrefix(`/youtube`)
      - traefik.http.routers.invidious.middlewares=invidious-stripprefix
      - traefik.http.middlewares.invidious-stripprefix.stripprefix.prefixes=/youtube
      - traefik.http.routers.invidious.entrypoints=websecure
      - traefik.http.routers.invidious.tls=true
```
The setting like above works well with Grafana, Nextcloud, etc. But in this case, when I try to enter https://docker/youtube, I receive the 404 page of Wordpress at https://docker/feed/popular address.

How to config it correctly?
