### ISSUE TITLE
[Bug] Logging in and registering don't work

### ISSUE THREAD

**Issue by TheSilkky** [iv-org/invidious#2091]
**Describe the bug**

Logging in or registering just redirects back to the home page without actually logging in.

**Steps to Reproduce**

Go to: https://invidious.silkky.cloud
Try to login or register.

**Logs**

Logs only show a normal POST request when trying to login, no error.

**Additional context**

Docker swarm mode

docker-compose:
```yml
version: '3.8'

services:

  database:
    image: postgres:13-alpine
    hostname: database
    volumes:
      - ./invidious-database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - database-backend
    deploy:
      placement:
        constraints:
          - node.labels.database-server == true
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s 
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    image: quay.io/invidious/invidious:latest
    hostname: invidious
    networks:
      - traefik-public
      - database-backend
#    logging:
#      driver: none
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
  
        # Access Router
        - "traefik.http.routers.invidious.rule=Host(`${INVIDIOUS_HOSTNAME}`)"
        - "traefik.http.routers.invidious.tls.certresolver=letsencrypt"
        - "traefik.http.routers.invidious.entrypoints=websecure"
        - "traefik.http.routers.invidious.middlewares=invidious-headers"
        - "traefik.http.routers.invidious.service=invidious-service"

        # Service
        - "traefik.http.services.invidious-service.loadbalancer.server.port=3000"
        - "traefik.http.services.invidious-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.invidious-service.loadbalancer.sticky.cookie.secure=true"
  
        # CSP Header middleware
        - "traefik.http.middlewares.invidious-headers.headers.contentSecurityPolicy=default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; manifest-src 'self'; media-src 'self' blob: https://*.googlevideo.com:443 https://*.youtube.com:443; child-src blob:"
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 4
        check_tables: true
        feed_threads: 4
        db:
          user: kemal
          password: ${DATABASE_PASSWORD}
          host: database
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: true
        popular_enabled: true
        login_enabled: true
        registration_enabled: true
        statistics_enabled: true
        default_user_preferences:
          dark_mode: true
          quality: dash
        domain: https://${INVIDIOUS_HOSTNAME}/

networks:
  traefik-public:
    external: true
  database-backend:
    driver: overlay
```

**Comment by TheFrenchGhosty** [comment]
Invidious isn't configured correctly. Start with that.

**Comment by TheSilkky** [comment]
More specifically? I made a new compose:

https://github.com/TheSilkky/invidious-swarm

**Comment by TheFrenchGhosty** [comment]
external_port, it should work fine otherwise

**Comment by TheSilkky** [comment]
I removed my web application firewall. Still not working:
```yml
version: '3.8'

services:

  database:
    image: postgres:10-alpine
    hostname: database
    volumes:
      - ./invidious-database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - ./sql:/config/sql
      - ./init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    networks:
      - database-backend
    deploy:
      placement:
        constraints:
          - node.labels.database-server == true
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s 
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    image: quay.io/invidious/invidious:latest
    hostname: invidious
    networks:
      - database-backend
      - traefik-public
#    logging:
#      driver: none
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
  
        # Access Router
        - "traefik.http.routers.invidious.rule=Host(`${INVIDIOUS_HOSTNAME}`)"
        - "traefik.http.routers.invidious.tls.certresolver=letsencrypt"
        - "traefik.http.routers.invidious.entrypoints=websecure"
        - "traefik.http.routers.invidious.service=invidious-service"

        # Service
        - "traefik.http.services.invidious-service.loadbalancer.server.port=3000"
        - "traefik.http.services.invidious-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.invidious-service.loadbalancer.sticky.cookie.secure=true"
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1 
        feed_threads: 1 
        check_tables: true 
        db:
          user: kemal 
          password: ${DATABASE_PASSWORD} 
          host: database 
          port: 5432 
          dbname: invidious 
        full_refresh: false 
        popular_enabled: true 
        login_enabled: true 
        registration_enabled: true 
        statistics_enabled: true 
        admin_email: ${ADMIN_MAIL} 
        https_only: true 
        external_port: 443 
        domain: https://${INVIDIOUS_HOSTNAME} 
        captcha_key: ${ANTI_KEY} 

networks:
  traefik-public:
    external: true
  database-backend:
    driver: overlay
```
