### ISSUE TITLE
How is the health of an instance checked?

### ISSUE THREAD

**Issue by TROMsite** [iv-org/invidious#2184]
I apologize if this is documented somewhere but I cannot find it. Here https://redirect.invidious.io/ I see the health of some instances but not ours (ytb.trom.tf) and I was wondering if I should do anything about that. This is my config:

```
channel_threads: 1
feed_threads: 1

db:
  user: ********
  password: ***********
  host: ***********
  port: ***********
  dbname: **************

full_refresh: false
https_only: true
domain: 
port: *******
host_binding: *********
statistics_enabled: true
force_resolve: ipv6
captcha_key: ************

#https://github.com/iv-org/invidious/blob/5c6911065845d2724c7826f3d663a6ee6c7d4774/src/invidious/helpers/helpers.cr#L129
default_user_preferences:
  dark_mode: true
  local: true
  locale: "en"
  comments: ["youtube",""]
  quality:  "dash"
  quality_dash: "1080p"
  default_home: "none"
  player_style: "youtube"
```
