### ISSUE TITLE
[Bug] Kemal user db unchangeable

### ISSUE THREAD

**Issue by clecle226** [iv-org/invidious#2238]
**Describe the bug**

There is no possibility to use a user other than kemal with docker 

**Steps to Reproduce**

In docker-compose:
```
  invidious-app:
    image: omarroth/invidious:latest
    container_name: invidious-app
    restart: on-failure
    expose:
      - 3000
    links:
      - db
    volumes:
      - $PWD/config/invidious.yml:/invidious/config/config.yml
    networks:
      - backend
      - proxy
```
In config.yml:
```
channel_threads: 1
check_tables: true
feed_threads: 1
db:
  user: invidious
  password: ***
  host: db
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:
```

**Logs**

```
invidious-app      | 2021-07-03 14:30:40 UTC [info] check_table: check_table: CREATE TABLE channels
invidious-app      | Unhandled exception: role "kemal" does not exist (PQ::PQError)
invidious-app      |   from lib/pg/src/pq/connection.cr:203:7 in 'handle_error'
invidious-app      |   from lib/pg/src/pq/connection.cr:186:7 in 'handle_async_frames'
invidious-app      |   from lib/pg/src/pq/connection.cr:162:7 in 'read'
invidious-app      |   from lib/pg/src/pq/connection.cr:157:7 in 'read'
invidious-app      |   from lib/pg/src/pq/query.cr:53:14 in 'initialize'
invidious-app      |   from lib/pg/src/pq/query.cr:49:5 in 'new'
invidious-app      |   from lib/pg/src/pg/connection.cr:30:7 in 'exec_all'
invidious-app      |   from src/invidious/helpers/helpers.cr:439:7 in 'check_table'
invidious-app      |   from src/invidious.cr:113:3 in '__crystal_main'
invidious-app      |   from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
invidious-app      |   from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
invidious-app      |   from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
invidious-app      |   from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

**Additional context**

Docker version 20.10.6, build 370c289
docker-compose version 1.28.6, build unknown

**Solution**
Why not use the current_user function in SQL files? The software connects to the database and modifies the owner according to the user connected by the software. 
FR: Pourquoi ne pas utiliser la fonction current_user dans les fichiers SQL? Le logiciel se connecte à la base de donnée et modifie le propriétaire en fonction de l'utilisateur connecté par le logiciel.

For example, for channels.sql: 
```
GRANT ALL ON TABLE public.channels TO current_user;
```
