### ISSUE TITLE
How to update config after deploying using Docker.

### ISSUE THREAD

**Issue by Jenni32222** [iv-org/invidious#2569]
In another issue I saw that INVIDIOUS_CONFIG env instead of the config.yml file is recommended, but how do I edit the config after I have deployed Invidious? For examle disabling new users.

**Comment by unixfox** [comment]
You just add more parameters to the INVIDIOUS_CONFIG env and restart the container.

**Comment by Jenni32222** [comment]
Thanks, can you please explain how to do this? Thanks in advance

**Comment by unixfox** [comment]
Add more parameters after this line: `INVIDIOUS_CONFIG: |`
For example if you wanted to disable the proxy then you would add the line `disable_proxy` like this:
```yaml
    environment:
      INVIDIOUS_CONFIG: |
        disable_proxy: false
```
