### ISSUE TITLE
Can't access admin prefs after adding user ID

### ISSUE THREAD

**Issue by tiritibambix** [iv-org/invidious#2836]
**Describe the question**
I'm trying to add my user ID as admin.

**Steps to Reproduce**
1. Install with
```
version: "3.3"
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - invidious
    volumes:
      - /srv/mypath/Invidious/postgresdata:/var/lib/postgresql/data
      - /srv/mypath/Invidious/config/sql:/config/sql
      - /srv/mypath/Invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    networks:
      - invidious
    mem_limit: 1024M
    cpus: 0.5
    ports:
      - "3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        full_refresh: false
        https_only: false
        domain:
      # external_port:
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres
  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgresdata:

networks:
  invidious:
```
2. Add [config.yml](https://github.com/iv-org/invidious/blob/master/config/config.example.yml) into  `/srv/mypath/Invidious/config`
3. Edit config.yml and add `admins: ["userID"]`
4. Can't access admin prefs.

Is `/srv/mypath/Invidious/config` the right place to put the config.yml ?
