### ISSUE TITLE
[Enhancement] Convey more structure in the DOM tree code.

### ISSUE THREAD

**Issue by mk-pmb** [iv-org/invidious#2837]
**Is your enhancement request related to a problem? Please describe.**

My browser injects a custom style sheet for me. I'd like to use that to re-style the related videos sidebar into a gallery view with multiple cards per row. This is harder than it should be:

* Lots of the containers have no descriptive class= or id=, so I have to use `#player-container ~ .pure-g` and couting selectors a lot.
* The sidebar entries each are a pair of a+h5 on the same level.

**Describe the solution you'd like**

* Let's name more stuff in the DOM.
* Let's wrap sidebar entries in a div.

**Describe alternatives you've considered**

* Have a bookmarklet transform the code.

**Additional context**

**Comment by mk-pmb** [comment]
Another obstacle is that all the `#player-container ~ .pure-g > :last-child > .h-box > a div.thumbnail + p` carry their own `style="width:100%"` attribute. Once we have descriptive CSS classes, let's please move that direct styling to the style sheet.

**Comment by mk-pmb** [comment]
Do we have to fix all at once, or could we introduce the class names progressively? What kind of rewrite is planned for the UI components?

**Comment by SamantazFox** [comment]
I think it's better if we implement them progressively. Makes changes easier to review, test and rollback if that broke something :)

Regarding the work in progress:
* Search filters: #2544.
* Channel pages (videos, channel playlists, related channels, etc...): #2546
* Footer: #2215
* User pages: #2377 plus another PR I haven't pushed yet (basically preferences + import/export + account management pages (password, tokens, subscriptions))

---

Also note that at the moment, the light/dark theme switching is based on CSS media queries, and that color definitions are almost always duplicated. For instance, links style is done like so:

```css
.light-theme a:hover,
.light-theme a:active,
.light-theme summary:hover {
  color: #075A9E !important;
}

@media (prefers-color-scheme: light) {
  .no-theme a:hover,
  .no-theme a:active,
  .no-theme summary:hover  {
    color: #075A9E !important;
  }
}


.dark-theme a:hover,
.dark-theme a:active,
.dark-theme summary:hover {
  color: rgb(0, 182, 240);
}

@media (prefers-color-scheme: dark) {
  .no-theme a:hover,
  .no-theme a:active {
    color: rgb(0, 182, 240);
  }
}
```

I know that this is far from optimal and should be cleaned by using `<property>: var(--variable);` with the corresponding `--variable` declaration in the `html` element CSS:


```css
html.light-theme {
  --link-color: #075A9E;
}

@media (prefers-color-scheme: light) {
  html.no-theme  {
    --link-color: #075A9E;
  }
}

html.dark-theme {
  --link-color: rgb(0, 182, 240);
}

@media (prefers-color-scheme: dark) {
  html.no-theme {
    --link-color: rgb(0, 182, 240);
  }
}

a:hover, a:active, summary:hover  {
  color: var(--link-color);
}
```
