### ISSUE TITLE
[Bug] Unhandled exception: could not find expected ':' at line 13, column 1, while scanning a simple key at line 12, column 1 (YAML::ParseException)

### ISSUE THREAD

**Issue by krtn0828** [iv-org/invidious#2838]
**Describe the bug**

An error occurs after building invidious with Docker and it does not start
Invidious is not displayed in the set domain (localhost: 3000)

**Steps to Reproduce**

1. Clone the repository
`git clone https://github.com/iv-org/invidious.git && cd invidious`
2. Build with docker-compose
`docker-compose up -d`

**Logs**

Container logs
```
  from src/invidious.cr:39:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Unhandled exception: could not find expected ':' at line 13, column 1, while scanning a simple key at line 12, column 1 (YAML::ParseException)
  from /usr/share/crystal/src/yaml/pull_parser.cr:339:7 in 'raise'
  from /usr/share/crystal/src/yaml/pull_parser.cr:122:7 in 'read_next'
  from /usr/share/crystal/src/yaml/parser.cr:105:5 in 'parse_scalar'
  from /usr/share/crystal/src/yaml/parser.cr:91:7 in 'parse_node'
  from /usr/share/crystal/src/yaml/parser.cr:141:43 in 'parse_mapping'
  from /usr/share/crystal/src/yaml/parser.cr:97:7 in 'parse_node'
  from /usr/share/crystal/src/yaml/parser.cr:76:31 in 'parse_document'
  from /usr/share/crystal/src/yaml/parser.cr:60:7 in 'parse'
  from /usr/share/crystal/src/yaml/nodes.cr:13:32 in 'parse'
  from from_yaml.cr:22:3 in 'parse_yaml'
  from /usr/share/crystal/src/yaml/from_yaml.cr:12:31 in 'from_yaml'
  from src/invidious/config.cr:127:14 in 'load'
  from src/invidious.cr:38:12 in '~CONFIG:init'
```

**Additional context**

OS: Ubuntu 20.04.3 LTS x86_64
Docker version: 20.10.12, build e91ed57
docker-compose version: 1.28.2, build 67630359

**Comment by unixfox** [comment]
Can you paste your docker-compose.yml file?

**Comment by krtn0828** [comment]
Sorry for my incomplete post
This is my docker-compose.yml: 
```
version: '3'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "localhost:3000:3000"
    restart: unless-stopped
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        domain:
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres

volumes:
  postgresdata:

networks:
  default:
    external:
      name: shared
```
There is no particular difference from the Invidious master branch except that the Ports section is set to "localhost:3000:3000".
