### ISSUE TITLE
[Bug] Dash playback/proxy problems on docker-swarm

### ISSUE THREAD

**Issue by dragonchaser** [iv-org/invidious#2842]
**Describe the bug**
When running invidious on docker-swarm behind traefik as reverse proxy. Video streams stop in firefox and chrome with the following error in the video overlay: 
```
The media could not be loaded, either because the server or network failed or because the format is not supported.
```
or 
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
```
in the devtools (after 10-15 minutes of playback with `disable_proxy=false` with `disable_proxy=["dash"]` playback does not even start and the error is displayed instantly. With `disable_proxy=true` playback works just fine. I am assuming this is either a caching issue in the server (e.g. cache underrun or an issue with the internal docker network).

**Steps to Reproduce**
1. Deploy invidious to docker-swarm with traefik configured and headers changed.
2. Click on any video to start playback
3. If `proxy_disabled=false` wait 10-15 minutes otherwise error will be displayed instantly

**Additional context**
 - Browser (if applicable): firefox, chromium, google-chrome
 - OS (if applicable): openSUSE, Arch

**Comment by unixfox** [comment]
Which docker image are you using?

**Comment by dragonchaser** [comment]
> Which docker image are you using?

`quay.io/invidious/invidious:latest-arm64`

**Comment by unixfox** [comment]
Can you let the "network" tab of the devtools opened and check for HTTP requests with errors?
Then post the screenshot of the network tab.

**Comment by dragonchaser** [comment]
![image](https://user-images.githubusercontent.com/1058116/151034486-1af6790c-ca6e-4bc3-a4e7-514dbc754097.png)

**Comment by unixfox** [comment]
Can you paste the video ID that you are testing?

**Comment by dragonchaser** [comment]
tRt5Ua4dQR0
But that is not related to a specific video.....

**Comment by unixfox** [comment]
Can you try with a non-music video like this one: https://www.youtube.com/watch?v=LsWwhmy8wf0?

**Comment by dragonchaser** [comment]
Same error, I already tried that. As said above, this is not related to a specific video.

**Comment by SamantazFox** [comment]
Could you please share the server logs?
In case you have nothing, use the `log_level` and `output` variables in the config.

**Comment by dragonchaser** [comment]
Config:
```
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        pool_size: 100
        disable_proxy: false
        db:
          user: <pgdatabase-user>
          password: <pgdatabase-password>
          host: invidious-postgres
          port: 5432
          dbname: <pgdatabase-invidiousdb>
        full_refresh: false
        registration_enabled: true
        login_enabled: true
        popular_enabled: true
        banner:
        port: 3000
        external_port: 443
        https_only: true
        domain: <domainofinstance.tld>
        statistics_enabled: false
        default_user_preferences:
          feed_menu: ["Popular", "Trending", "Subscriptions", "Playlists"]
          autplay: true
          continue: true
          continue_autoplay: true
          default_home: Trending
          local: true
          quality: hd720
          quality_dash: 720p
```

Log:
```
2022-01-26 11:17:29 UTC [info] 200 GET /ggpht/ytc/<redacted>122.32ms
2022-01-26 11:17:32 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 193.89ms
2022-01-26 11:18:02 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 145.47ms
2022-01-26 11:18:32 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 154.07ms
2022-01-26 11:19:02 UTC [info] 206 GET /videoplayback?expire=1643217447&<redacted> 94639.57ms
2022-01-26 11:19:02 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 199.61ms
2022-01-26 11:19:33 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 175.09ms
2022-01-26 11:20:03 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 160.22ms
2022-01-26 11:20:33 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 147.31ms
2022-01-26 11:21:03 UTC [info] 206 GET /videoplayback?expire=1643206624&<redacted> 10914327.13ms
2022-01-26 11:21:04 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 161.04ms
2022-01-26 11:21:34 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 176.39ms
```

**Comment by SamantazFox** [comment]
> ```
> 2022-01-26 11:19:02 UTC [info] 206 GET /videoplayback?expire=1643217447&<redacted> 94639.57ms
> 2022-01-26 11:21:03 UTC [info] 206 GET /videoplayback?expire=1643206624&<redacted> 10914327.13ms
> ```

mmmh, ok.

Can you please try to add `use_quic: false` to your config?

**Comment by dragonchaser** [comment]
Does not solve it.... same issue again.

**Comment by martadinata666** [comment]
is it working without traefik? i mean access it locally. because i also on swarm but don't really seeing this issue.

**Comment by dragonchaser** [comment]
@martadinata666 nope, I tried it with standard port 3000 and had the same issue, what are you running your swarm on?

**Comment by martadinata666** [comment]
i'm on minimal docker swarm. I used to get your error few times, because some network issue. Like the page loaded but the video request cant keep up because lag response to `videos.google.bla2` url.
Let me share my compose. 

My compose
```
version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - invidious
    volumes:
      - ./db1:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
      - ./backup:/backup
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    deploy:
      placement:
        constraints: [ node.role == manager ]

  app:
    image: quay.io/invidious/invidious:latest-arm64
    configs:
      - source: invidious.yml
        target: /invidious/config/config.yml
    networks:
      - invidious
    #ports:
    #  - 127.0.0.1:3000:3000
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        full_refresh: false
        https_only: false
        domain:
      #  external_port: 443
    #healthcheck:
    #  test: wget -nv --tries=1 --spider http://127.0.0.1:3000/feed/trending || exit 1
    #  interval: 60s
    #  timeout: 5s
    #  retries: 2
    depends_on:
      - postgres
    deploy:
      placement:
        constraints: [ node.hostname == rpi4 ]
  apache:
    image: 192.168.0.2:5050/dedyms/apache:fcgid
    ports:
      - 8383:443
    configs:
      - source: apache.conf
        target: /etc/apache2/sites-available/000-default-ssl.conf
    networks:
      - invidious
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

networks:
  invidious:
    name: invidious

configs:
  apache.conf:
    file: ./000-default.conf
```

Apache reverse proxy
```
<VirtualHost *:443>
        #Protocols h2 http/1.1
        Protocols http/1.1
        SSLEngine on
        SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
        SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
  
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        
        ProxyPreserveHost On
        ProxyPass "/" "http://app:3000/"
        ProxyPassReverse "/" "http://app:3000/"
        
        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>
        
        <Location />
          Order allow,deny
          Allow from all
        </Location>

</VirtualHost>

```
