### ISSUE TITLE
[Bug] Service Unaccessable to LAN with Docker Install

### ISSUE THREAD

**Issue by PersonMeetup** [iv-org/invidious#2869]
**Describe the bug**

When running Invidious as a Docker image, trying to connect to Invidious from another computer on the same local network will have its connection refused.

**Steps to Reproduce**

1. On computer A, set up Invidious as a normal Docker install.
2. Confirm successful installation by checking `localhost:3000`
3. On computer B, connect to computer A's IP under port 3000 (ex: `10.1.1.5:3000`)
4. Recieve `ERR_CONNECTION_REFEUSED`

**Additional context**

- Server OS: Linux Mint 20.3
- Running [Gitea as a Docker image](https://docs.gitea.io/en-us/install-with-docker/) (which defaults to port 3000 as well) allows other computers on the network to connect
- I am *very* new to Docker so this may be a mistake I caused

**Comment by k-sareen** [comment]
I've recently setup a very similar use case. First can you check if the port specified is open for connections from whatever subet you're connect from (presumably `10.1.1.0/24`)? If it is, then the gitea instance may be interfering. Can you try using a different port for invidious in the `docker-compose.yml` then? As an aside, I would recommend using a reverse proxy such as nginx and assigning an intranet domain name for your gitea and invidious instances. I simply use [the nginx config from the invidious documentation](https://docs.invidious.io/NGINX-Reverse-Proxy.md) (with a self-signed SSL cert instead of Let's Encrypt since this is an intranet website) which works quite well for my use case.

**Comment by PersonMeetup** [comment]
> Can you try using a different port for invidious in the `docker-compose.yml` then?

Sadly, no. It seems when I go to change the port I am unable to connect to Invidious, even on the server itself. As for the ports, it may also be worth bringing up that I don't have both Invidious and Gitea up simultaneously. Port 3000 in this case is only open when Invidious is running.

Thank's for bringing up intranet domain names btw, I'll be talking a look into it!

**Comment by k-sareen** [comment]
Hmm -- that sounds odd. Did you bind it correctly [here](https://github.com/iv-org/invidious/blob/master/docker-compose.yml#L22)? I believe you would only have to change the port on the left from `3000` to something else, for example:
```
ports:
  - "127.0.0.1:9000:3000"
```
to use port `9000` on your local machine to connect to the invidious instance. I just tested it out and `localhost:9000` redirected to the invidious docker instance.

Also Re: intranet domain names, you'll have to add the domain names to your DNS for it to work properly. I use a pihole for my DNS so it's pretty simple, but you can simply edit your local DNS files on your machines as well.

**Comment by PersonMeetup** [comment]
Thanks for the clarification, turns out I changed the wrong port! I'm able to set Invidious' port to 9000 and connect through localhost, but I'm still unable to connect on the other computer...

**Comment by k-sareen** [comment]
Note that you need to allow port `3000` or `9000`, whichever you use, in your firewall. Since you're using Linux Mint, I believe its default firewall is `ufw`. You'll have to open the port from the firewall (and ideally you only allow your private IPs to access the port, but you can temporarily make it public just to test).

**Comment by PersonMeetup** [comment]
Ports were allowed (more than that, I had the firewall down) but nothing changed. 

Just because I feel like I have to be doing something wrong, especially since Invidious seems to be the only image giving me problems (even running a static web server image seems to be doing fine), I'm going to dump the current `docker-compose.yml` I'm using on the off-chance I messed with something I shouldn't have.

```
version: "2.4"
services:
  postgres:
    image: postgres:10
    restart: always
    networks:
      - invidious
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: always
    networks:
      - invidious
    mem_limit: 1024M
    cpus: 0.5
    ports:
      - "127.0.0.1:9000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        full_refresh: false
        https_only: false
        domain:
      # external_port:
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgresdata:

networks:
  invidious:

```
