### ISSUE TITLE
[Bug] User unable to change its own password

### ISSUE THREAD

**Issue by Malakai-DB** [iv-org/invidious#2875]
Hello,

Just FYI, before opening the issue, I did :
  * Read the FAQ!
  * Use the search function to check if there is already an issue open for your problem!

**Describe the bug**
I created a user on my own invidious instance and tried to change it's password from the webui without success.

**Steps to Reproduce**
1. Login with your user
2. Go to : http(s)://your.instance/change_password
3. Input your current password once and your new password twice
4. After hitting "Change password" you are sent back to homepage without effect (password is still the old one)

**Logs**
There is no error on the application logs, nor on the postgres database logs. Nothing special in the browser console either.
In the application logs we can see the following : 
```
2022-02-08 15:25:19 UTC [info] 200 GET /preferences?referer=%2Ffeed%2Fsubscriptions 1.83ms
2022-02-08 15:25:20 UTC [info] 200 GET /api/v1/auth/subscriptions?fields=authorId 1.68ms
2022-02-08 15:25:24 UTC [info] 200 GET /change_password?referer=%2Ffeed%2Fsubscriptions 879.17µs
2022-02-08 15:25:24 UTC [info] 200 GET /api/v1/auth/subscriptions?fields=authorId 3.47ms
2022-02-08 15:25:28 UTC [info] 200 POST /api/v1/auth/notifications?fields=videoId,title,author,authorId,publishedText,published,authorThumbnails,liveNow 178034.63ms
```
I activated debug logs, but I can still not see any error / warning that could explain why the password isn't changed.

**Screenshots**
Not applicable.

**Additional context**
Invidious is installed with docker compose (and postgres database also) behind an apache2 reverse proxy.
After setting up the database, I imported the sql scripts found [here](https://github.com/iv-org/invidious/tree/master/config/sql) to create the necessary tables and set the rights.
Everything else is working as expected (subscriptions, watching videos, creating playlists, etc).

I am on version 2022.02.02-0ca3337@master using the docker image from quay.io/invidious/invidious

**Comment by unixfox** [comment]
Can you post your config.yml without the personal/confidential information?

**Comment by SamantazFox** [comment]
I'd say it's probably a side effect of #2492

**Comment by Malakai-DB** [comment]
> Can you post your config.yml without the personal/confidential information?

```
channel_threads: 1
feed_threads: 1
output: STDOUT
log_level: info
db:
  user: dbuser
  password: dbpassword
  host: postgres
  port: 5432
  dbname: mydb
database_url: postgres://dbuser:dbpassword@postgres:5432/mydb
decrypt_polling: true
full_refresh: false
use_pubsub_feeds: false
popular_enabled: false
captcha_enabled: true
login_enabled: true
registration_enabled: false
statistics_enabled: false
admins:
- myuser
external_port: 80
default_user_preferences:
  annotations: false
  annotations_subscribed: false
  autoplay: false
  captions:
  - ""
  - ""
  - ""
  comments:
  - youtube
  - ""
  continue: false
  continue_autoplay: true
  dark_mode: ""
  latest_only: false
  listen: false
  local: false
  locale: en-US
  max_results: 40
  notifications_only: false
  player_style: invidious
  quality: hd720
  quality_dash: auto
  default_home: ""
  feed_menu:
  - Subscriptions
  - Playlists
  automatic_instance_redirect: false
  region: US
  related_videos: true
  sort: published
  speed: 1.0
  thin_mode: false
  unseen_only: false
  video_loop: false
  extend_desc: false
  volume: 100
  vr_mode: true
  show_nick: true
  save_player_pos: false
dmca_content: []
check_tables: false
cache_annotations: false
hsts: true
disable_proxy: false
modified_source_code_url: ""
force_resolve: 
port: 3000
host_binding: 0.0.0.0
pool_size: 100
use_quic: false
cookies: ""
captcha_api_url: https://api.anti-captcha.com
```

> I'd say it's probably a side effect of https://github.com/iv-org/invidious/pull/2492

Sadly I am not knowledgeable enough to understand what is discussed in that pull request, but is this meaning that on a future docker image pull, the problem should be solved?
