### ISSUE TITLE
[Bug] K8S - ClusterIP service causes crash loop

### ISSUE THREAD

**Issue by IDevJoe** [iv-org/invidious#2970]
**Describe the bug**
When a ClusterIP service exists prior to the start of the pod on K8S, the `port` config option is automatically overwritten with the full TCP protocol. This results in a casting error, and causes a crash loop. The issue is not fixed by manually setting the port option in the config.

**Steps to Reproduce**
1. Create a ClusterIP service that references a future deployment
2. Create a deployment
3. Observe crash loop

**Pod Log**
```
Config.port failed to parse tcp://10.245.184.101:3000 as Int32
```

**Additional context**

K8S Version: v1.22.7 on DigitalOcean

Service config:
```
apiVersion: v1
kind: Service
metadata:
  name: invidious
  namespace: invidious
  labels:
    app: invidious
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: invidious
  type: ClusterIP
```

Deployment Config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
  namespace: invidious
  labels:
    app: invidious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      containers:
      - name: invidious
        image: quay.io/invidious/invidious:latest
        env:
        - name: INVIDIOUS_CONFIG
          value: |
            channel_threads: 1
            check_tables: true
            feed_threads: 1
            db:
              dbname: invidious
              user: kemal
              password: kemal
              host: postgres
              port: 5432
            full_refresh: false
            https_only: true
            domain: [Redacted]
            external_port: 443
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        ports:
          - name: http
            containerPort: 3000
```
