### ISSUE TITLE
[Bug] Invalid memory access

### ISSUE THREAD

**Issue by confuzeus** [iv-org/invidious#3003]
**Describe the bug**

I'm getting an *Invalid memory access (signal 11)* error on startup.

**Steps to Reproduce**

I followed the [installation guide](https://docs.invidious.io/installation/) using docker-compose on amd64.

Once I run `docker-compose up -d`, in the logs I see the error message and Invidous fails to start.

There was already an issue at [#1791](https://github.com/iv-org/invidious/issues/1791) but it's been marked as resolved even though nothing has been resolved.

Is there any way to fix this or is the app currently in a broken state?

**Comment by unixfox** [comment]
Please post your docker-compose.yml

**Comment by confuzeus** [comment]
I'm using the docker-compose.yml from the repo with minor changes:

```yml
# Warning: This docker-compose file is made for development purposes.
# Using it will build an image from the locally cloned repository.
#
# If you want to use Invidious in production, see the docker-compose.yml file provided
# in the installation documentation: https://docs.invidious.io/Installation.md

version: "3"
services:

  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:12000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: secret
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        https_only: false
        domain: mydomain.com
        captcha_enabled: false
        admin_email: me@mydomain.com
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
