### ISSUE TITLE
[Bug] cast from Nil to Bool failed, at /usr/share/crystal/src/json/any.cr:156:5:156 (TypeCastError)

### ISSUE THREAD

**Issue by eravion** [iv-org/invidious#3066]
Hello.
I have an issue with my instance on this URL https://monyoutube.ravion.org/watch?v=AxhE2A6S1uk
It looks to be ok with https://invidious.flokinet.to/watch?v=AxhE2A6S1uk 

Version : 2022.04.30-1d25c55

**Describe the bug**
Error message

**Steps to Reproduce**
1. Go to https://monyoutube.ravion.org/watch?v=AxhE2A6S1uk
2. See error

**Logs**
Title: `cast from Nil to Bool failed, at /usr/share/crystal/src/json/any.cr:156:5:156 (TypeCastError)`
Date: `2022-04-30T20:16:25Z`
Route: `/watch?v=AxhE2A6S1uk`
Version: `2022.04.30-1d25c55 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
cast from Nil to Bool failed, at /usr/share/crystal/src/json/any.cr:156:5:156 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:156:5 in &#39;as_bool&#39;
  from src/invidious/views/watch.ecr:210:95 in &#39;handle&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from src/invidious/helpers/handlers.cr:30:37 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/ext/kemal_static_file_handler.cr:167:15 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/share/crystal/src/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/share/crystal/src/fiber.cr:146:11 in &#39;run&#39;
  from ???
```
</p>
</details>

**Additional context**
My docker-compose.yml file

```yaml
version: '3'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: XXX
      POSTGRES_USER: XXX
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        decrypt_polling: false
        use_quic: false
        default_home: Subscriptions
        db:
          user: XXX
          password: XXX
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        domain:
    depends_on:
      - postgres
volumes:
  postgresdata:
```
