### ISSUE TITLE
[Bug] No thumbnails on video progress bar

### ISSUE THREAD

**Issue by haorenxu** [iv-org/invidious#3298]
My video progress bar misses thumbnails which only display transparent boxes.

<img width="518" alt="Screen Shot 2022-09-02 at 9 12 58 PM" src="https://user-images.githubusercontent.com/33184148/188153826-a831965d-e8c5-4384-9928-e6686c0cd24a.png">

My instance is on a VPS which is proxied by Cloudflare Tunnel. And here is my docker config:

```
version: "3"
services:
  invidious:
    image: quay.io/invidious/invidious
    container_name: invidious
    restart: always
    ports:
      - "49153:3000"
    depends_on:
      - invidious-db
    environment:
      INVIDIOUS_CONFIG: |
        database_url: postgres://kemal:kemal@invidious-db:5432/invidious
        popular_enabled: false
        admins: ["user"]
        default_user_preferences:
          default_home: Subscriptions
          autoplay: true
          continue_autoplay: false
          quality: dash
          quality_dash: 1080p
  invidious-db:
    image: postgres
    container_name: invidious-db
    restart: always
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    volumes:
      - data:/var/lib/postgresql/data
      - ./invidious/config/sql:/config/sql
      - ./invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
volumes:
  data:
```
