### ISSUE TITLE
[Bug] Docker configuration will be ignored

### ISSUE THREAD

**Issue by MalteKiefer** [iv-org/invidious#3392]
I have created a `docker` config.
But the configuration `local`, `dark_mode`, `disable_proxy` and `default_home` are simply ignored. I cannot explain why the configuration is not applied.

```yaml
version: "3"
services:

  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: FXRCwbzweRXAHAgQWZiEQwHXJnwNdhUKbT4wKG2U4reAY
          host: invidious-db
          port: 5432
        check_tables: true
        local: true
        feed_menu: ["Popular", "Trending", "Subscriptions", "Playlists"]
        default_home: Popular
        dark_mode: true
        https_only: true
        disable_proxy: false
        registration_enabled: false
        login_enabled: false
        banner: "Feel free to participate in this service with donations: <a href='https://liberapay.com/beli3ver'>https://liberapay.com/beli3ver</a>"
        region: "DE"
        comments: ["youtube", "reddit", ""]
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: FXRCwbzweRXAHAgQWZiEQwHXJnwNdhUKbT4wKG2U4reAY
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
