### ISSUE TITLE
[Bug] Videos missing in Subscriptions tab

### ISSUE THREAD

**Issue by thebozzcl** [iv-org/invidious#3395]
**Describe the bug**
Recently, I've noticed my subscribed videos list hasn't been getting as many new videos as usual. Many of the channels I follow upload pretty frequently. I looked at one of them, and the channel view shows several new videos that aren't appearing in the Subscriptions section.

I've tried a few things to see if I could fix it:
* Different Docker images, in case there was a fix my current one is missing
* Enabling full refresh

**Steps to Reproduce**
1. Open the "Subscriptions" tab
2. Look for a channel that hasn't uploaded videos in a few days, and open their channel directly
3. See new videos that are missing from the Subscriptions tab

**Logs**
I'm really not sure what logs are relevant here. I raised the logging level to "all" for a bit but it's so much I'm not really sure what to look at. LMK what I should share.

**Screenshots**
![screenshot 1](https://user-images.githubusercontent.com/1743524/201972038-f46e1f03-4bf8-4aca-92b3-ebc63a00c569.png)
![screenshot 2](https://user-images.githubusercontent.com/1743524/201972064-5943ef0b-1df5-4faf-890c-7738ac827c63.png)

**Additional context**
Invidious version: `2022.11.02-09942de @ master`

Running via `docker-compose`, managed by Portainer.

**Comment by unixfox** [comment]
If your instance is reachable from the internet then enable pubsub: `use_pubsub_feeds: true`
Don't forget to configure domain, hmac_key and external_port to 443 if invidious is behind a proxy.
See https://docs.invidious.io/configuration/

**Comment by thebozzcl** [comment]
Seems to be working fine with PubSub enabled. The missing videos haven't shown up, but at least I'm seeing requests for the webhook endpoint in the logs so it's doing *something*. I'm gonna close this for now and re-open if I notice further issues.

**Comment by corincorvus** [comment]
Hey, 

i have the same problem today after a 3 weeks it ran good.
I clustered 12 containers with a config and nightly restart over cron.

The new Videos not coming up since 1 hour.

"use_pubsub_feeds: true" are already true

i already restarted all, tested it with new deploy, but nothing helps. I can see the new videos, if i use the search, but in supscriptions the videos are not visible.

maybe my config is wrong?

Thanks

```
---
channel_threads: 24
channel_refresh_interval: 5m
feed_threads: 6
output: STDOUT
log_level: error
db:
  user: 
  password: 
  host: 
  port: 5432
  dbname: 
database_url: 
decrypt_polling: false
full_refresh: false
https_only: true
hmac_key: 
domain: yt.c-lab.one
use_pubsub_feeds: true
popular_enabled: true
captcha_enabled: true
login_enabled: true
registration_enabled: false
statistics_enabled: false
external_port: 443
default_user_preferences:
  annotations: false
  annotations_subscribed: false
  autoplay: true
  captions:
  - ""
  - ""
  - ""
  comments:
  - youtube
  - ""
  continue: false
  continue_autoplay: true
  dark_mode: auto
  latest_only: false
  listen: false
  local: false
  locale: de
  watch_history: true
  max_results: 40
  notifications_only: false
  player_style: youtube
  quality: dash
  quality_dash: 1080p
  default_home: Popular
  feed_menu:
  - Popular
  - Trending
  - Subscriptions
  - Playlists
  automatic_instance_redirect: false
  region: DE
  related_videos: true
  sort: published
  speed: 1.0
  thin_mode: false
  unseen_only: false
  video_loop: false
  extend_desc: false
  volume: 100
  vr_mode: true
  show_nick: true
  save_player_pos: true
dmca_content: []
check_tables: true
cache_annotations: false
hsts: true
disable_proxy: false
enable_user_notifications: true
modified_source_code_url: ""
force_resolve:
port: 3000
host_binding: 0.0.0.0
pool_size: 100
use_innertube_for_captions: false
cookies: ""
playlist_length_limit: 500
jobs:
  clear_expired_items:
    enable: true
  notification:
    enable: true
  pull_popular_videos:
    enable: true
  refresh_channels:
    enable: true
  refresh_feeds:
    enable: true
  statistics_refresh:
    enable: true
  subscribe_to_feeds:
    enable: true
  update_decrypt_function:
    enable: true

```
