### ISSUE TITLE
[Bug] Raspberry Pi4 DietPi - Docker (linux/arm64) does not match the detected host platform (linux/arm/v8)

### ISSUE THREAD

**Issue by bbsixzz** [iv-org/invidious#3712]
**Describe the bug**
`! invidious The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested`
**Steps to Reproduce**
`docker compose up -d`
**Logs**
No logs

**Screenshots**
<img width="377" alt="Screenshot 2023-03-29 at 01 24 03" src="https://user-images.githubusercontent.com/47334163/228389081-cb332c48-6b65-454c-a107-d9a8afa6efba.png">
<img width="1172" alt="Screenshot 2023-03-29 at 01 28 45" src="https://user-images.githubusercontent.com/47334163/228389311-f9cfc1fc-56b8-491c-a781-4f6d0dad672b.png">
**Additional context**
```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest-arm64
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    dns:
      - 192.168.1.1
    ports:
      - 3000:3000
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        external_port: 3000
        domain: 192.168.1.2
        channel_threads: 2
        # channel_refresh_interval: 20m
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:

```
