### ISSUE TITLE
[Bug] Subscriptions setup only work in Incognito or via reverse proxy

### ISSUE THREAD

**Issue by hugalafutro** [iv-org/invidious#3772]
**Describe the bug**

I am trying to run local instance for my use only, when trying to setup Subscriptions (or saving config) it just logs me out. Everything works ok in incognito mode or via reverse proxy (which I do not want to use). Disabling all extensions and deleting browsing data doesn't make difference (thought it's some extension when it worked in incognito)

**Steps to Reproduce**
1. Login to local instance of invidious
2. Click the bell
3. You're logged out
4. (if you previously managed to import subs you will still see the videos even logged out.)

**Logs**
no errors in docker log neither browser log

**Screenshots**
[Video_2023-04-28_074313.webm](https://user-images.githubusercontent.com/30209689/235074343-8e5ddac1-6f30-4e5e-bc5c-f0d39004e5b7.webm)

**Additional context**
 - Browser (if applicable): vivaldi
 - OS (if applicable): win11

**Comment by unixfox** [comment]
How did you install invidious in the first place?

**Comment by hugalafutro** [comment]
Sorry should have mentioned I use docker, following the official install documentation, with this docker-compose.yml:
```
version: "3"
services:

  invidious:
    container_name: invidious
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3543:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: ${DB_USER_INV}
          password: ${DB_PW_INV}
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: ${DB_USER_INV}
      POSTGRES_PASSWORD: ${DB_PW_INV}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
