### ISSUE TITLE
[Question] Invidious ignoring config.yml file settings

### ISSUE THREAD

**Issue by 7zx** [iv-org/invidious#4174]
**Describe the bug**
I'm running Invidious on Debian 12 using Docker, i renamed the config file on `/invidious/config/` from `config.example.yml` to `config.yml` , but the changes that i am making on the config.yml are not being applied to the Invidious instance: [**invidious.polido.pt**](https://invidious.polido.pt/)

**Steps to Reproduce**
Go to `/invidious/config/config.yml` and edit the file using nano (all of this being done as root).
Removing the #'s from what i want to change from true to false and then saving the file.
Rebooting both containers using `docker restart invidious_invidious_1 invidious_invidious-db_1`.

**Additional context**
I'm using Cloudflare Tunnels, but this should not be whats causing the issue.
`config.yml` file (i added it to a .txt file so you don't have to download it): **https://files.catbox.moe/woabad.txt**

**Expected to happen**
Login and register and popular feed are disabled, but they are working, which it's not suposed.

**Comment by 7zx** [comment]
My `docker-compose.yml` file:

```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "ieV7ohyo2ar4eiFoz3Oo"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
