### ISSUE TITLE
[Bug] regression in latest Docker image: database server hostname lookup fails

### ISSUE THREAD

**Issue by salfter** [iv-org/invidious#4179]
**Describe the bug**
quay.io/invidious/invidious:069e91d2a609b1df94bdfbb693335969b2a281d8 fails to start up.  It appears that it's not looking up the database server's hostname properly:

```
Unhandled exception:  (DB::ConnectionRefused)
  from lib/sqlite3/src/sqlite3/connection.cr:10:11 in '->'
  from lib/db/src/db/pool.cr:214:27 in 'build_resource'
  from /usr/share/crystal/src/int.cr:545:11 in 'build_database'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Cannot establish connection (PQ::ConnectionError)
  from lib/pg/src/pq/connection.cr:34:9 in 'new'
  from lib/pg/src/pg/connection.cr:13:23 in '->'
  from lib/db/src/db/pool.cr:214:27 in 'build_resource'
  from /usr/share/crystal/src/int.cr:545:11 in 'build_database'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Hostname lookup for postgres.container failed: No address found (Socket::Addrinfo::Error)
  from /usr/share/crystal/src/socket/address.cr:368:33 in 'new'
  from lib/pg/src/pg/connection.cr:13:23 in '->'
  from lib/db/src/db/pool.cr:214:27 in 'build_resource'
  from /usr/share/crystal/src/int.cr:545:11 in 'build_database'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```

**Steps to Reproduce**
Run ```docker start -a invidious``` after pulling the latest image and the message given above shows up.  Roll the container back to quay.io/invidious/invidious:60fae015d8b5e4b0bfac8306065db07f93c4c661, though, and it'll start up properly. 

**Additional context**
I'm running Invidious on Flatcar Container Linux, with PostgreSQL and Nginx running in separate containers on the same host.

**Comment by salfter** [comment]
Just checked the latest images...this bug is still present as of 8087e64dfe8353bd7ee224b1985fcb1d8a47122c.

**Comment by unixfox** [comment]
Please paste your config.yml without the credentials and any personal information.

**Comment by salfter** [comment]
I think this is the stock config.yml.  I've filtered out the comments and empty lines:

```
db:
  user: kemal
  password: ***
  host: invidious-db
  port: 5432
  dbname: invidious
domain:
https_only: false
channel_threads: 1
full_refresh: false
feed_threads: 1
jobs:
  clear_expired_items:
    enable: true
  refresh_channels:
    enable: true
  refresh_feeds:
    enable: true
hmac_key: "CHANGE_ME!!"
default_user_preferences:
```

Config options for the container are set by passing INVIDIOUS_CONFIG in the environment upon creation. It sets the following values:

```
channel_threads: 1
check_tables: true
feed_threads: 1
db:
  dbname: invidious
  user: kemal
  password: ***
  host: postgres.container
  port: 5432
full_refresh: false
https_only: false
domain:
hmac_key: ***
```
