### ISSUE TITLE
[Question] Failing installation on arm (raspberry pi 4) (YAML::ParseException)

### ISSUE THREAD

**Issue by Martinligabue** [iv-org/invidious#4220]
**Describe the bug**

The docker-compose up fails when starting. I followed https://docs.invidious.io/installation/#docker-compose-method-production and edited the file to include arm image, and I changed the ports to 3000.

I checked for other issues, faqs, and online, I only found https://github.com/iv-org/invidious/issues/3397 but it seems a different issue.

**Steps to Reproduce**

1. Follow official instructions, editing the docker compose for directly access Invidious on a raspberry, so on arm.
2. Run docker-compose up
3. `Unhandled exception: Couldn't parse (DBConfig | Nil) at line 2, column 3 (YAML::ParseException)`

(I couldn't understand what's the file being parsed, so I couldn't troubleshoot more)

**Logs**

```
Pulling invidious (quay.io/invidious/invidious:latest-arm64)...
latest-arm64: Pulling from invidious/invidious
579b34f0a95b: Pull complete
85860900f24c: Pull complete
c3d735c0e05e: Pull complete
ea395f528aea: Pull complete
301bb7a01776: Pull complete
4e18aea5fffe: Pull complete
8c839bf42558: Pull complete
b34682617574: Pull complete
eff604296d76: Pull complete
bd964ab5c4cb: Pull complete
e56be536a094: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:311a194a70a9e485451924701240632c63e8e1cdf7813f68e8e25a9d2230e2b0
Status: Downloaded newer image for quay.io/invidious/invidious:latest-arm64
Creating invidious_invidious-db_1 ... done
Creating invidious_invidious_1    ... done
Attaching to invidious_invidious-db_1, invidious_invidious_1
invidious-db_1  | The files belonging to this database system will be owned by user "postgres".
invidious-db_1  | This user must also own the server process.
invidious-db_1  |
invidious-db_1  | The database cluster will be initialized with locale "en_US.utf8".
invidious-db_1  | The default database encoding has accordingly been set to "UTF8".
invidious-db_1  | The default text search configuration will be set to "english".
invidious-db_1  |
invidious-db_1  | Data page checksums are disabled.
invidious-db_1  |
invidious-db_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
invidious-db_1  | creating subdirectories ... ok
invidious-db_1  | selecting dynamic shared memory implementation ... posix
invidious-db_1  | selecting default max_connections ... 100
invidious-db_1  | selecting default shared_buffers ... 128MB
invidious-db_1  | selecting default time zone ... Etc/UTC
invidious-db_1  | creating configuration files ... ok
invidious_1     | Unhandled exception: Couldn't parse (DBConfig | Nil) at line 2, column 3 (YAML::ParseException)
invidious-db_1  | running bootstrap script ... ok
invidious-db_1  | performing post-bootstrap initialization ... ok
invidious_1     |   from /usr/lib/crystal/core/yaml.cr:88 in 'raise'
invidious_1     |   from /usr/lib/crystal/core/yaml/from_yaml.cr:285:3 in 'load'
invidious_1     |   from src/invidious.cr:60:12 in '~CONFIG:init'
invidious_1     |   from /usr/lib/crystal/core/crystal/once.cr:25:54 in '__crystal_once'
invidious_1     |   from src/invidious/user/cookies.cr:9:35 in '__crystal_main'
invidious_1     |   from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
invidious_1     |   from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
invidious-db_1  | syncing data to disk ... ok
invidious-db_1  |
invidious-db_1  |
invidious-db_1  | Success. You can now start the database server using:
invidious-db_1  |
invidious-db_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
invidious-db_1  |
invidious-db_1  | initdb: warning: enabling "trust" authentication for local connections
invidious-db_1  | You can change this by editing pg_hba.conf or using the option -A, or
invidious-db_1  | --auth-local and --auth-host, the next time you run initdb.
invidious-db_1  | waiting for server to start....2023-10-31 21:49:55.911 UTC [49] LOG:  starting PostgreSQL 14.9 (Debian 14.9-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
invidious-db_1  | 2023-10-31 21:49:56.113 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
invidious-db_1  | 2023-10-31 21:49:56.166 UTC [50] LOG:  database system was shut down at 2023-10-31 21:49:52 UTC
invidious-db_1  | 2023-10-31 21:49:56.224 UTC [49] LOG:  database system is ready to accept connections
invidious-db_1  |  done
invidious-db_1  | server started
invidious-db_1  | CREATE DATABASE
invidious-db_1  |
invidious-db_1  |
invidious-db_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-invidious-db.sh
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious_1     | Unhandled exception: Couldn't parse (DBConfig | Nil) at line 2, column 3 (YAML::ParseException)
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE INDEX
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE TYPE
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  | CREATE TABLE
invidious-db_1  | GRANT
invidious-db_1  |
invidious-db_1  | 2023-10-31 21:49:58.980 UTC [49] LOG:  received fast shutdown request
invidious-db_1  | waiting for server to shut down....2023-10-31 21:49:58.983 UTC [49] LOG:  aborting any active transactions
invidious-db_1  | 2023-10-31 21:49:58.994 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
invidious-db_1  | 2023-10-31 21:49:58.995 UTC [51] LOG:  shutting down
invidious-db_1  | 2023-10-31 21:49:59.134 UTC [49] LOG:  database system is shut down
invidious-db_1  |  done
invidious-db_1  | server stopped
invidious-db_1  |
invidious-db_1  | PostgreSQL init process complete; ready for start up.
invidious-db_1  |
invidious-db_1  | 2023-10-31 21:49:59.263 UTC [1] LOG:  starting PostgreSQL 14.9 (Debian 14.9-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
invidious-db_1  | 2023-10-31 21:49:59.264 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
invidious-db_1  | 2023-10-31 21:49:59.264 UTC [1] LOG:  listening on IPv6 address "::", port 5432
invidious-db_1  | 2023-10-31 21:49:59.271 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
invidious-db_1  | 2023-10-31 21:49:59.283 UTC [83] LOG:  database system was shut down at 2023-10-31 21:49:59 UTC
invidious-db_1  | 2023-10-31 21:49:59.302 UTC [1] LOG:  database system is ready to accept connections
invidious_1     |   from /usr/lib/crystal/core/yaml.cr:88 in 'raise'
invidious_1     |   from /usr/lib/crystal/core/yaml/from_yaml.cr:285:3 in 'load'
invidious_1     |   from src/invidious.cr:60:12 in '~CONFIG:init'
invidious_1     |   from /usr/lib/crystal/core/crystal/once.cr:25:54 in '__crystal_once'
invidious_1     |   from src/invidious/user/cookies.cr:9:35 in '__crystal_main'
invidious_1     |   from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
invidious_1     |   from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
invidious_invidious_1 exited with code 1
```
Then it repeats while trying to restart as the container is set to restart unless stopped.

**Screenshots**

**Additional context**

 - OS (if applicable): Debian GNU/Linux 11 (bullseye) aarch64

**Comment by Martinligabue** [comment]
```
version: "3"
services:

  invidious:
    #image: quay.io/invidious/invidious:latest
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
#I changed the previous two lines lines as per the arm architecture
    restart: unless-stopped
    ports:
      #- "127.0.0.1:3000:3000"
     - "3000:3000"
     # I changed the previous as it's a local installation
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "I changed this"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:

```

I kept the default admins and psws as it's only reachable from my internal network
