### ISSUE TITLE
[Bug] broken captcha on fresh docker install

### ISSUE THREAD

**Issue by doums** [iv-org/invidious#4230]
### Describe the bug

Hi, I just set up an invidious instance through docker. All works fine. But on the login/register form, the captcha image is broken. Image link is `data:image/png;base64,`
Note that I'm using Caddy as a reverse proxy to handle HTTPS.

Fallback to text captcha works as expected.

This is my config:
```
       INVIDIOUS_CONFIG: |
         port: 3000
         external_port: 443
         domain: sub.mydomain.com
         https_only: true
         log_level: Info
         db:
           dbname: invidious
           user: inv
           password: 1234
           host: invidious-db
           port: 5432
         check_tables: true
         statistics_enabled: true
         registration_enabled: true
         login_enabled: true
         captcha_enabled: true
         admins: [""]
         channel_threads: 4
         channel_refresh_interval: 30m
         feed_threads: 4
         hmac_key: "xxxxx"
         default_user_preferences:
           default_home: Subscriptions
           save_player_pos: true
```

![image](https://github.com/iv-org/invidious/assets/6359431/52107ce6-85c9-4c07-9d47-cbfe9efe846e)
