### ISSUE TITLE
docker.io/library/postgres:14 .. ERROR: missing signature key

### ISSUE THREAD

**Issue by beshoo** [iv-org/invidious#4291]
While doing docker-compose up
for this docker-compose file
```

version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest


    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "CHANGE_ME!!"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:9090/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:

```

I have the following error:

```
[MAX]root:[/download/youtube/invidious]docker-compose up
Pulling invidious-db (docker.io/library/postgres:14)...
ERROR: missing signature key
```

PS: my docker v : Docker version 17.09.1-ce, build 19e2cf6
I know it is old , but this is the one I can run on centos7 cloudLinux server 

Please advice
