### ISSUE TITLE
[Bug] configs in docker-compose.yml not reflecting

### ISSUE THREAD

**Issue by dannykorpan** [iv-org/invidious#4721]
**Describe the bug**
I've set up a docker instance following [your](https://docs.invidious.io/installation/#docker) documentation with a caddy proxy. My docker-compose.yml looks like this:
```
...
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: MYSECUREPASSWORD
          host: invidious-db
          port: 5432
        check_tables: true
        external_port: 443
        domain: invidious.mydomain.com
        https_only: true
        statistics_enabled: false
        hmac_key: "SECUREKEY"
        quality: dash
        quality_dash: best
...
```

As soon as the instance is ready, the quality options are not reflected to the UI, see attached screenshot. I'm not logged in and trying it in incognito mode.

If I log in and set the preferences manually it's saved and working, but not in "anonymous" mode without user account.

**Steps to Reproduce**
Follow the documentation

**Logs**

**Screenshots**
<img width="166" alt="SCR-20240531-rgtm-2" src="https://github.com/iv-org/invidious/assets/8004507/383b1b72-5e01-448e-800c-3bf8d92ed9e5">
