### ISSUE TITLE
After update, I am getting Error 502

### ISSUE THREAD

**Issue by wael-t** [iv-org/invidious#4994]
I was able to access Invidious but videos were not playing, so I proceed to update my instance adding the recent   inv_sig_helper container as advised on the website. However, know I am getting Error 502 when I visit my instance.

This is my docker compose file (self hosted on home server), did I do anything wrong: 

```
version: "3"
services:
  invidious:
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    container_name: invidious
    hostname: invidious
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: **************
          host: invidious-db
          port: 5432
        check_tables: true
        hmac_key: "******************"
        signature_server: inv_sig_helper:12999
        admins: ["videos"]
        thin_mode: false
        external_port: 443
        domain: videos.mydomain.com
        https_only: true
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    networks:
      - invidious-tunnel
    depends_on:
      - invidious-db
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

      
  invidious-db:
    image: docker.io/library/postgres
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - /Users/wael/docker/invidious/postgresdata:/var/lib/postgresql/data
    networks:
      - invidious-tunnel
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kalima00
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
   postgresdata:

networks:
  invidious-tunnel:
    external: true
```

**Steps to Reproduce**
