### ISSUE TITLE
[Bug] Video Resolution always defaults to 'medium'and no other options are visible.

### ISSUE THREAD

**Issue by Softbox44** [iv-org/invidious#5101]
**Describe the bug**
Video Resolution always defaults to 'medium'and no other options are visible.

**Steps to Reproduce**
1. Launch docker containers
2. call internal IP with port 3000
3. Search for video
4. Watch video

**Logs**:  My compose file
```

 version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: CgsxT01oVDVOMmpjbyia_NO4BjIKCgJHQhIEGgAgIA%3D%3D
        po_token: xx
        quality: dash
        quality_dash: auto
        speed: 1.25
        volume: 25
        # external_port:
        # domain:
        # https_only: false
        statistics_enabled: false
        hmac_key: "HMAC2024?"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - /srv/2T_JBOD/Invidious/db-data:/var/lib/postgresql/data
      - /srv/2T_JBOD/Invidious/db-config:/config/sql
      - /srv/2T_JBOD/Invidious/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: xx
      POSTGRES_PASSWORD: xx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
**Screenshots**

**Additional context**
