### ISSUE TITLE
HTTP 500 in /videoplayback with DASH on local instance

### ISSUE THREAD

**Issue by alindt** [iv-org/invidious#5123]
**Describe the bug**
- HTTP 500 in /videoplayback with `quality=dash` on both dev/release with docker (local instance)
- `The media could not be loaded, either because the server or network failed or because the format is not supported.`
- 1 in 50-ish videos will play with DASH but the audio language is usually not English if multiple tracks are available

**Steps to Reproduce**
Use `quality=dash` for any video

**Logs**
[devtools-console.txt](https://github.com/user-attachments/files/18229400/console-export.txt)
[devtools-network.json](https://github.com/user-attachments/files/18230173/devtools-network.json)
[invidious-container-logs.txt](https://github.com/user-attachments/files/18229808/invidious-container-logs.txt)

**Additional context**
 - Browser: Firefox 133.0.3 (64-bit)
 - OS: Linux Mint 22 (64-bit)
 - Docker: 26.1.3 (linux/amd64)

**docker-compose.yaml**
```yaml
# Warning: This docker-compose file is made for development purposes.
# Using it will build an image from the locally cloned repository.
#
# If you want to use Invidious in production, see the docker-compose.yml file provided
# in the installation documentation: https://docs.invidious.io/installation/

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - inv_sig_helper
      - db
    ports:
      - "3777:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "AThibeeQuah7hees9oit"
        visitor_data: CgtXUUtEV3...........
        po_token: MpQBc3sRAoQIJM...........
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
```
