### ISSUE TITLE
[Question] videojs The media could not be loaded, either because the server or network failed or because the format is not supported - Missing inv_sig_helper

### ISSUE THREAD

**Issue by cgmastertecnology** [iv-org/invidious#5124]
image latest
i got error when reproducing media, any video, dash and not:

![image](https://github.com/user-attachments/assets/052202e1-de2a-4b2f-a612-929011bfed1d)
![image](https://github.com/user-attachments/assets/d63d31f0-7fd3-4a93-8c92-e753b1f4117d)

my stack is:

```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - 3300:3000
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "---------------"
        visitor_data: CgthSHNaS0lnN---------------------
        po_token: MpQB1As04ahmyT3UM-----------------------------

    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - /home......../invidious/postgres:/var/lib/postgresql/data
      - /home......../invidious/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
