### ISSUE TITLE
[Question] DASH not working

### ISSUE THREAD

**Issue by richardcrbb** [iv-org/invidious#5125]
Hi there, I made my own instance in my RPI5 with docker, using this documentation:

[https://docs.invidious.io/installation/#docker-compose-method-production](url)

I ran this command 

`docker run quay.io/invidious/youtube-trusted-session-generator`

I used the following .yml

```
version: "3"
services:

  invidious:
    #image: quay.io/invidious/invidious:latest
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: ****
          password: ****************************************
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: **************************************** as per recommendation of the pre-install command
        po_token: **************************************** as per recommendation of the pre-install command
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: **************************************** as per recommendation of the pre-install command
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: ******
      POSTGRES_PASSWORD: **************************************** 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```

after installation everything works but the dash option on most of the videos, not autoplay or play next video.

In Invidious settings I set the following:

![Screenshot from 2024-12-27 09-48-20](https://github.com/user-attachments/assets/f8c94c12-d854-4d13-aab2-69dd5e90b7a1)

Did I configured the .yml file wrong? Can I fix it without rm the container? or do I have to make a new install?

I can only watch videos in bad resolution, please help.

Thanks
