### ISSUE TITLE
Some channels videos in french

### ISSUE THREAD

**Issue by Seeings** [iv-org/invidious#5134]
I've a problem where some channels videos, notably JayzTwoCents channel (not sure if there are more, not tested), are in french rather than the original audio, on my self-hosted invidious instance.

It seems to have started around 2-3 weeks ago, when looking back at videos from that channel. Not sure as to why other than I believe it has something to do with the point of when the inv_sig_helper container came into the docker-compose.yml setup. But I can't be sure.

<details>
<summary>This is how my docker-compose.yml looks like:</summary>

```yml
services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: <hidden>
          password: <hidden>
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: <hidden>
        po_token: <hidden>
        external_port: 443
        domain: <hidden>
        https_only: true
        enable_user_notifications: false
        use_pubsub_feeds: true
        use_innertube_for_captions: true
        admins: <hidden>
        hmac_key: <hidden>
        playlist_length_limit: 1500
        registration_enabled: false
        default_user_preferences:
          quality: dash
          quality_dash: best
          dark_mode: dark
          related_videos: false
          volume: 50
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - TZ=Europe/Stockholm
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: <hidden>
      POSTGRES_PASSWORD: <hidden>
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```

</details>
