### ISSUE TITLE
[Enhancement] Allow invidious_companion entries to contain trailing slash /

### ISSUE THREAD

**Issue by FibreFoX** [iv-org/invidious#5204]
This probably is just an enhancement and not a bug, but maybe you see it differently.

I've set up a network local instance of invidious with the invidious-companion via docker

```yml
services:
  invidious:
    image: quay.io/invidious/invidious:companion
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: xxxx
          user: xxxx
          password: xxxx
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        - private_url: "http://invidious_companion:8282/"
          public_url: "http://invidious:8282/"
        invidious_companion_key: "MY_KEY"
        https_only: false
        statistics_enabled: false
        hmac_key: "MY_HMAC"
        popular_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 300s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      invidious-db:
        condition: service_healthy

  invidious_companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
      SERVER_SECRET_KEY: "MY_KEY"
      HOST: "0.0.0.0"
      SERVER_BASE_URL: "http://invidious:8282"
    restart: unless-stopped
    ports:
      - "8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    volumes:
      - ./youtubei.js:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: xxxx
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```

The problem comes from this part:
```
        invidious_companion:
        - private_url: "http://invidious_companion:8282/"
          public_url: "http://invidious:8282/"
```

When having any slash at the end, the internal URLs are just appended, which means that internal communication is having double slashes in the URL. This is some example log output from docker:
```
invidious_companion-1  | <-- POST /youtubei/v1/player
invidious_companion-1  | --> POST /youtubei/v1/player 200 150ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 200 GET /watch?v=zh2nN1xlaco 804.53ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 200 GET /js/playlist_widget.js?v=1741765276338 598.67µs
invidious-1            | 2025-03-12 07:41:16 UTC [info] ytimg_pool: Creating a new HTTP pool for "https://i.ytimg.com"
invidious_companion-1  | <-- GET //latest_version?id=zh2nN1xlaco&itag=18&local=true&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4=
invidious_companion-1  | --> GET //latest_version?id=zh2nN1xlaco&itag=18&local=true&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4= 404 1ms
invidious_companion-1  | <-- GET //api/manifest/dash/id/zh2nN1xlaco?local=true&unique_res=1&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4=
invidious_companion-1  | --> GET //api/manifest/dash/id/zh2nN1xlaco?local=true&unique_res=1&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4= 404 0ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 200 GET /api/v1/storyboards/zh2nN1xlaco?height=90 12.67ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 304 GET /vi/1WNz1Hru_9I/mqdefault.jpg 99.82ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 304 GET /vi/Qy1IWJcwwSc/mqdefault.jpg 95.18ms
invidious_companion-1  | <-- GET //api/manifest/dash/id/zh2nN1xlaco?local=true&unique_res=1&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4=
invidious_companion-1  | --> GET //api/manifest/dash/id/zh2nN1xlaco?local=true&unique_res=1&check=FTBtReP-qBimYotPdqi7YXIyG28NZG0QmrgZUggCAG4= 404 0ms
invidious-1            | 2025-03-12 07:41:16 UTC [info] 200 GET /apple-touch-icon.png?v=d0433c83 141.96µs
invidious-1            | 2025-03-12 07:41:16 UTC [info] 200 GET /favicon-16x16.png?v=d0433c83 72.86µs
invidious-1            | 2025-03-12 07:41:18 UTC [info] 304 GET /vi/zh2nN1xlaco/maxres.jpg 1789.92ms
invidious-1            | 2025-03-12 07:41:18 UTC [info] 200 GET /api/v1/comments/zh2nN1xlaco?format=html&hl=de&thin_mode=false 193.12ms
invidious-1            | 2025-03-12 07:41:19 UTC [info] 200 GET /api/v1/auth/subscriptions 15.64ms
invidious_companion-1  | <-- GET /healthz
```

This results in the wrong requests `GET //latest_version` and `GET //api/manifest/dash/id`. I tried to add routes with double slashes to the companion myself via local docker images, and it worked, which made me double-check my configured values.

Either the documentation should warn about this, or the system should check (and refuse) URLs with trailing slashes, or it should get rid of trailing slashes itself (which would be the best solution from a user perspective).
