### ISSUE TITLE
[Question] Can only play videos while logged out (local instance)

### ISSUE THREAD

**Issue by pflavio** [iv-org/invidious#5272]
**Describe the bug**

Today my self-hosted Invidious instance started behaving strangely after I had to restart the VM it's hosted on via Docker. I'm only able to play videos when I'm not logged into my local Invidious account. As soon as I'm logged in I can see my subscriptions and my playlists, but can't actually play videos ("The media could not be loaded, either because the server or network failed or because the format is not supported."). Unfortunately there aren't any obvious errors in the logs of invidious, db or sig helper as far as I can tell and videos do work fine when I sign out. 
It was working fine for months without issues (except the DASH and "this helps protect our community" stuff - thanks for resolving those so quickly) and I did not make any config changes, I only restarted the VM (or rather the VM host due to maintenance which lead to the VM restarting as well). I tried disabling         the domain and https_only settings but no luck.

**Steps to Reproduce**
1. Go to my invidious instance (either via domain name or via IP:port)
2. Click on any video and watch it - it works
3. Log in with my username and password on the top right (button changes to log out)
4. Click on any video and try to watch it - see error "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Logs**

**Screenshots**
not needed

**Additional context**
 - Browser: I tried both Ironwolf and ungoogled-chromium
 - OS: Invidious is hosted on a Debian 12 VM (kernel 6.1.0-34-amd64) in Docker (only Invidious and an instance of Portainer Agent are running on this machine) with the following config file:

```
services:

  invidious:
    image: quay.io/invidious/invidious:latest #master
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: xxx
        po_token: xxx
        external_port: 443
        #domain: invidious.xxx.com
        #https_only: true
        # statistics_enabled: false
        hmac_key: xxx
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest #master-5d3c7a4
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - /root/docker/invidious/config/sql:/config/sql
      - /root/docker/invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
