### ISSUE TITLE
Can't register user

### ISSUE THREAD

**Issue by GTP95** [iv-org/invidious#5343]
Hello everyone,
I had an Invidious instance that I left rotting for a while and entered a non-working state, so I decided to start afresh. 
To do this, I first stashed my modifications inside the directory I cloned the repo into with `git stash` to preserve my configuration. Then, I pulled the updates and applied the stash, and verified that `docker-compose.yml` contained my edits. I then proceeded to stop and deleted the Docker containers, and deleted the corresponding Docker images to make sure the latest versions were going to be pulled. Finally, I executed `docker compose up -d`. It worked, but every time I attempt to register a new user, I just get redirected to the "trending" page, and nothing else seems to happen. 
Inspecting the container's output with `docker logs -f` didn't show anything useful. I enabled the stats inside `docker-compose.yml` and recreated the containers, to make sure that creating new users is enabled. This is how the stats look like:
```JSON
{"version":"2.0","software":{"name":"invidious","version":"2025.05.17-f07859e","branch":"(HEAD detached at v2.20250517.0)"},"openRegistrations":true,"usage":{"users":{"total":1,"activeHalfyear":1,"activeMonth":0}},"metadata":{"updatedAt":1749328909,"lastChannelRefreshedAt":1749328118},"playback":{}}
```
And this is how my `docker-compose.yml` file looks like:
```YML
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: [REDACTED]
          password: [REDACTED]
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: [REDACTED]
        po_token: [REDACTED]
        # external_port:
        domain: [REDACTED]
        # https_only: false
        statistics_enabled: true
        hmac_key: [REDACTED]
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: [REDACTED]
      POSTGRES_PASSWORD: [REDACTED]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```

Could you please help me in fixing this?

**Comment by syeopite** [comment]
Your local changes shouldn't be relevant at all since you're pulling an image instead of building one locally.

Within the invidious logs on what request is it returning a 302 redirect?

**Comment by GTP95** [comment]
I think that my instance is logging to stdout (this is the default behaviour, right?), so here's what I got by inspecting the container's output during a registration/login attempt:

```
2025-06-07 21:26:50 UTC ÄinfoÅ 200 GET /api/v1/trending 247.36ms
2025-06-07 21:27:03 UTC ÄinfoÅ 200 GET /login?referer=%2Ffeed%2Fpopular 268.92µs
2025-06-07 21:27:16 UTC ÄinfoÅ 302 POST /login?referer=%2Ffeed%2Fpopular&type=invidious 58.6ms
2025-06-07 21:27:16 UTC ÄinfoÅ 200 GET /feed/popular 316.15µs
2025-06-07 21:27:20 UTC ÄinfoÅ 200 GET /api/v1/trending 301.24ms
```

Should I increase the logging level?

Edit: I tried increasing the log level by modifying the `Docker-compose.yml` file in the following way:

```YML
logging:
      options:
        max-size: "1G"
        max-file: "4"
        log_level: Debug
```

But when trying to recreate the containers, I got the following error: `Error response from daemon: unknown log opt 'log_level' for json-file log driver`
