### ISSUE TITLE
[Bug] All videos result in many 302 redirects and NS_ERROR_REDIRECT_LOOP error

### ISSUE THREAD

**Issue by aquova** [iv-org/invidious#5350]
**Describe the bug**
I've had a self-hosted Invidious installation on my home server for some time, but had let it get into in a state where it no longer functioned. I'm trying to get it up and running today, but I'm still unable to watch any videos at all. Any time I attempt to watch one, I can see a large number of 302 redirect errors spat out, eventually resulting in a NS_ERROR_REDIRECT_LOOP error (on Firefox. I tried on Chromium and received its equivalent error as well). I still get the error if I attempt to switch from DASH to Medium quality. I was originally using `invidious-sig-helper` but have switched to the `compainion` image, using the documented set up guide. Neither seem to work. I've also cleared out most of my existing configuration, cleared cookies on the client, nothing.

**Logs**
Here is an example of my docker-compose.yml:

```
services:
  invidious:
    image: quay.io/invidious/invidious:master
    restart: unless-stopped
    container_name: invidious
    ports:
      - 3000:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
          - private_url: "http://companion:8282"
            public_url: "https://mydomain.net"
        invidious_companion_key: <output of pwgen 16 1>
        hmac_key: <different output of pwgen 16 1>
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  companion:
    image: quay.io/invidious/invidious-companion:latest
    restart: unless-stopped
    environment:
      - SERVER_SECRET_KEY=<same token as invidious_companion_key>
    ports:
      - 8282:8282
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ./cache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

```

One other thing to note is that the companion image does regularly spit out the following warning:

```
[WARNING] No URLs found for adaptive formats. Falling back to other YT clients.
[WARNING] Trying fallback YT client TV_SIMPLY
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/c2ffd358-9633-4872-af4d-f5e48d599eb7)

**Additional context**
Client is using Arch Linux with Firefox 139
