### ISSUE TITLE
How to unfreeze subscriptions?

### ISSUE THREAD

**Issue by cyberchief1984** [iv-org/invidious#674]
How do I unfreeze my subscription feed? I;m not using the official instance. Somebody froze it.

**Comment by fliegentoeter** [comment]
Happens to me on the official instance on a daily basis. Seems like subspriptions are only updated twice a day or even less...

**Comment by omarroth** [comment]
> I;m not using the official instance

Mind providing which instance you are using?

Otherwise I expect it's an issue with higher load. There's a couple things I have in mind to try that should fix the issue, although it may be a couple days before I can take a look at it.

**Comment by cyberchief1984** [comment]
I am using https://invidious.13ad.de.

**Comment by PureTryOut** [comment]
I'm using a private self-hosted one, I'm the only user, and I haven't seen an update to my subscriptions since last week. If I go to an individual channel the newest videos do show up however.

**Comment by omarroth** [comment]
What does your `config.yml` look like?

**Comment by PureTryOut** [comment]
```
channel_threads: 1
feed_threads: 1
db:
  user: ****
  password: ****
  host: ****
  port: ****
  dbname: ****
full_refresh: false
https_only: false
domain:
```
