### ISSUE TITLE
Video stats: conditional formatting

### ISSUE THREAD

**Issue by corona-nova** [iv-org/invidious#707]
**request related to a problem**
many-digit numbers are hard to read and digest

perhaps color-graded numbers depending on the value, 
similar to stack-overflow or the like,
bar graphs are an alternative
[greasyfork ratings-bar-with-power-meter (only works when polymer disabled)](https://greasyfork.org/en/scripts/2302-youtube-video-ratings-bar-with-power-meter)

**alternatives**
more stats into on thumbnails, whether to make it the default , or a preference to avoid clutter

maybe implement via html-class groupings and CSS
```css
.views9 { color: #some-color; }
.views8 { color: #some-color-between-9&7; }
.views7 { color: #some-color; }
```

whether to reduce clutter ,
instead of truncating the precision,
reducing the font-weight after 3? [significant digits](https://en.wikipedia.org/wiki/Significant_Digits#Rounding_and_decimal_places)

a perhaps more sane way to sort parameters that 
are often exponential (view count #of likes, dislikes)
is to use  logarithmic based binning/grouping
