### ISSUE TITLE
configuration for a minimalistic and maximum privacy instance

### ISSUE THREAD

**Issue by pred2k** [iv-org/invidious#828]
Hi, i want to run a new invidious instance that offers the basic Video-proxying functionality of invidious, respect viewers privacy as good as possible and remove most distrations.
Just let a user watch videos that were shared to him/her or let him/her search a specific ones.
Nothing more.

So, what can simple be done via the `config/config.yml` is disabling the registration, the top endpoint (show most watched videos on this instance) and the Feed-Menu.
That would result to:
```yaml
https_only: true
login_enabled: false
registration_enabled: false
top_enabled: false
feed_menu: []
```
Now i need some help with these points:
* Enable proxy mode by default (and maybe remove the posibility to disable it).
* Remove any video suggestions. Because they are "toxic". (see https://thenextweb.com/google/2019/10/15/mozilla-unveils-28-horror-stories-about-youtubes-recommendation-algorithm/)

What i also do on my HTTP reverse proxy is:
* Remove `https://*.googlevideo.com:443` from Content Security Policy (CSP) Header to avoid connections to google.

Does anyone has other suggestions that can be done without forking invidious?

**Comment by omarroth** [comment]
I would recommend looking at #415 for the unsolved points. In your config:

```yaml
default_user_preferences:
  local: true
  related_videos: false
```

**Comment by pred2k** [comment]
i'v decided for this configuration atm:

```yaml
https_only: true

# disable user registration. keep no user-data!
registration_enabled: false
login_enabled: false

# disable most watched videos on this instance:
top_enabled: false
# remove stupid trending or popluar videos:
feed_menu: []

default_user_preferences:
  # enable proxy mode:
  local: true
  # offer best quality as default:
  quality: dash
  # remove any "toxic" video suggestion:
  related_videos: false
  # completely disable (hate) comments (can't be re-enabled by users atm):
  comments: ["",""]
```
So far as i understand that disables all options where user data could been generated at invidious.
The videos that are beeing watched on the instance are cached and saved in the db.
Can this caching be disabled?

i also tested a more strict Content-Security-Policy (CSP) and removed the referer completely on my reverse proxy Caddy:
```
proxy / invidious:3000 {
   header_downstream Content-Security-Policy "default-src data: 'self' 'unsafe-inline' 'unsafe-eval'; media-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; block-all-mixed-content"
   header_downstream Referrer-Policy no-referrer
}
```

Another idea i have is to run the container as read_only and drop capabilities via the `docker-compose.yaml`:
```
    read_only: true
    cap_drop:
      - ALL
```
